Client/Client/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grantgoal/', include("grantgoal.urls"))
]

Client/grantgoal/urls.py
from django.urls import path
from grantgoal import views

app_name = "gg"

urlpatterns = [
    path("client/list/grantgoal/", views.ListGrantGoalClient.as_view(), name = "client_list_gg"),
    path("client/detail/grantgoal/<int:pk>/", views.DetailGrantGoalClient.as_view(), name = "detail_list_gg"),
    path("client/create/grantgoal/", views.CreateGrantGoalClient.as_view(), name = "create_gg_cl"),


]

api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    path('v1/list/grantgoal', views.ListGrantGoalAPIView.as_view(), name="list_gg_api"),
    path('v1/create/grantgoal', views.CreateGrantGoalAPIView.as_view(), name="create_gg_api"),
    path('v1/detail/grantgoal/<int:pk>', views.DetailGrantGoalAPIView.as_view(), name="detail_gg_api"),
    path('v1/update/grantgoal/<int:pk>', views.UpdateGrantGoalAPIView.as_view(), name="update_gg_api"),
    path('v1/delete/grantgoal/<int:pk>', views.DeleteGrantGoalAPIView.as_view(), name="delete_gg_api"),

]

pem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

examen2/Client/ToDo/models.py
from django.db import models

# Create your models here.

Client/grantgoal/forms.py
from django import forms

CHOICES_STATE = {
    ("NS", "NOT STARTED"),
    ("IP", "IN PROCESS"),
    ("DN", "DONE")
}

CHOICES_PRIORITY = {
    ("HIGH", "HG"),
    ("MIDDLE", "MD"),
    ("LOW", "LW")
}


class CreateGrantGoalClientForm(forms.Form):
    ggname = forms.CharField(max_length=32, widget= forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el grantgoal name!"}))
    description = forms.CharField(max_length=128, widget= forms.Textarea(attrs={"type":"text", "class":"form-control", "row": 3, "placeholder":"Escribe el grantgoal description!"}))
    days_duration = forms.IntegerField(widget= forms.NumberInput(attrs={"type":"number", "class":"form-control"}))
    state = forms.CharField(max_length=16, widget=forms.Select(choices=CHOICES_STATE, attrs={"type":"select", "class":"form-select form-control"}))
    priority = forms.CharField(max_length=16, widget=forms.Select(choices=CHOICES_PRIORITY, attrs={"type":"select", "class":"form-select form-control"}))
    status = forms.BooleanField(widget = forms.CheckboxInput(attrs={"type":"checkbox"}))
    slug = forms.SlugField(widget= forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el grantgoal slug!"}))

examen2/Client/ToDo/forms.py
from django import forms

CHOICES_LEVEL = (
    ("HIGH", "High"),
    ("MEDIUM", "Medium"),
    ("LOW", "Low"),
)

CHOICES_STATE = (
    ("PENDING", "Pending"),
    ("IN PROGRESS", "In Progress"),
    ("DONE", "Done"),
)

class CreateTaskForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Type the title of your task"})
    )
    description = forms.CharField(
        max_length=600,
        widget=forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Type a description for your task"})
    )
    due_date = forms.DateField(
        widget=forms.DateInput(attrs={"type": "date", "class": "form-control", "placeholder": "Select Due Date"})
    )
    priority = forms.ChoiceField(
        choices=CHOICES_LEVEL,
        widget=forms.Select(attrs={"class": "form-select form-control"})
    )
    state = forms.ChoiceField(
        choices=CHOICES_STATE,
        widget=forms.Select(attrs={"class": "form-select form-control"})
    )
    user = forms.ChoiceField(
        choices=[],
        widget=forms.Select(attrs={"class": "form-select form-control"})
    )
    area = forms.ChoiceField(
        choices=[],
        widget=forms.Select(attrs={"class": "form-select form-control"})
    )
    
class AreaForm(forms.Form):
    area_name = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Area Name"}))
    description = forms.CharField(max_length=128, required=False, widget=forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Area description"}))

Client/grantgoal/views.py
from django.shortcuts import render, redirect
from django.views import generic
import requests
from .forms import CreateGrantGoalClientForm

# Create your views here.

class CreateGrantGoalClient(generic.View):
    template_name = "grantgoal/create_gg_cl.html"
    context = {}
    url = "http://localhost:8000/api/v1/list/grantgoal"
    response = None
    payload = {}
    form_class = CreateGrantGoalClientForm
    
    def get(self, request):
        self.context = {
            "form": self.form_class
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request):
        self.payload = {
                "ggname": request.POST['ggname'],
                "description": request.POST['description'],
                "days_duration": request.POST['days_duration'],
                "priority": request.POST['priority'],
                "state": request.POST['state'],
                "status": request.POST['status'],
                "slug": request.POST['slug'],
                "user": 1 #Change this to the users data
        }
        self.response = requests.post(url=self.url, data=self.payload)
        return redirect("gg:client_list_gg")


class ListGrantGoalClient(generic.View):
    template_name = "grantgoal/list_gg_cl.html"
    url = "http://localhost:8000/api/v1/list/grantgoal"
    response = None
    context = {}
    
    def get(self, request):
        self.response = requests.get(url = self.url)
        self.context = {
            "grantgoals": self.response.json()
        }
        return render(request, self.template_name, self.context)
    
class DetailGrantGoalClient(generic.View):
    template_name = "grantgoal/detail_gg_cl.html"
    context = {}
    url = "http://localhost:8000/api/v1/detail/grantgoal/"
    response = None
    
    def get(self, request, pk):
        self.url = self.url + f'{pk}'
        self.response = requests.get(url = self.url)
        self.context = {
            "grantgoal": self.response.json()
        }
        return render(request, self.template_name, self.context)

examen2/Client/ToDo/views.py
from django.shortcuts import render, redirect
from django.views import generic
import requests
from .forms import CreateTaskForm, AreaForm
# Create your views here.
class ListTasksClient(generic.View):
    template_name = "ToDo/list_todo_cl.html"
    base_url = "http://localhost:8000/api/tasks/"
    response = None
    context = {}
    
    def get(self, request):
        filter_params = {}
        selected_endpoint = request.GET.get('endpoint')
        url = self.base_url
        
        # Determine which endpoint to use based on selected option
        if selected_endpoint == 'ids':
            url += 'ids/'
        elif selected_endpoint == 'id-titles':
            url += 'id-titles/'
        elif selected_endpoint == 'unresolved':
            url += 'unresolved/'
        elif selected_endpoint == 'resolved':
            url += 'resolved/'
        elif selected_endpoint == 'userids':
            url += 'userids/'
        elif selected_endpoint == 'resolved-userids':
            url += 'resolved/userids/'
        elif selected_endpoint == 'unresolved-userids':
            url += 'unresolved/userids/'
        else:
            # Default to all tasks
            pass
        
        self.response = requests.get(url=url)
        self.context = {
            "todo": self.response.json()
        }
        return render(request, self.template_name, self.context)

class CreateTasksClient(generic.CreateView):
    template_name = "ToDo/create_todo_cl.html"
    url = "http://localhost:8000/api/tasks/create/"
    users_url = "http://localhost:8000/api/users/"
    areas_url = "http://localhost:8000/api/areas/"
    context = {}
    form_class = CreateTaskForm
    
    def get(self, request):
        users_response = requests.get(self.users_url)
        areas_response = requests.get(self.areas_url)
        
        users = [(user['id'], f"{user['first_name']} {user['last_name']}") for user in users_response.json()]
        areas = [(area['id'], area['area_name']) for area in areas_response.json()]
        
        form = self.form_class()
        form.fields['user'].choices = users
        form.fields['area'].choices = areas
        
        self.context = {
            "form": form
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request):
        payload = {
            "title": request.POST['title'],
            "description": request.POST['description'],
            "due_date": request.POST['due_date'],
            "priority": request.POST['priority'],
            "state": request.POST['state'],
            "user": request.POST['user'],
            "area": request.POST['area']
        }
        response = requests.post(url=self.url, json=payload)  
        print(payload);
        return redirect("td:client_list_td")
    
class DetailTaskClient(generic.View):
    template_name = "ToDo/detail_todo_cl.html"
    context = {}
    url = "http://localhost:8000/api/tasks/"
    response = None
    
    def get(self, request, pk):
        self.url = self.url + f'{pk}'
        self.response = requests.get(url = self.url)
        self.context = {
            "todo": self.response.json()
        }
        return render(request, self.template_name, self.context)

class UpdateTasksClient(generic.View):
    template_name = "ToDo/update_todo_cl.html"
    url = "http://localhost:8000/api/tasks/"
    users_url = "http://localhost:8000/api/users/"
    areas_url = "http://localhost:8000/api/areas/"
    context = {}
    form_class = CreateTaskForm
    
    def get(self, request, pk):
        task_response = requests.get(self.url + f'{pk}/')
        task_data = task_response.json()
        
        users_response = requests.get(self.users_url)
        areas_response = requests.get(self.areas_url)
        
        users = [(user['id'], f"{user['first_name']} {user['last_name']}") for user in users_response.json()]
        areas = [(area['id'], area['area_name']) for area in areas_response.json()]
        
        form = self.form_class(initial=task_data)
        form.fields['user'].choices = users
        form.fields['area'].choices = areas
        
        self.context = {
            "form": form,
            "task_id": pk
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request, pk):
        payload = {
            "title": request.POST['title'],
            "description": request.POST['description'],
            "due_date": request.POST['due_date'],
            "priority": request.POST['priority'],
            "state": request.POST['state'],
            "user": request.POST['user'],
            "area": request.POST['area']
        }
        response = requests.put(url=self.url + f'{pk}/update/', json=payload)  
        return redirect("td:client_list_td")

class DeleteTasksClient(generic.View):
    template_name = "ToDo/delete_todo_cl.html"
    url = "http://localhost:8000/api/tasks/"

    def get(self, request, pk):
        task_response = requests.get(f"{self.url}{pk}/")
        task_data = task_response.json()

        context = {
            "task": task_data
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        try:
            response = requests.delete(f"{self.url}{pk}/delete/")
            response.raise_for_status()  # Raise an exception for HTTP errors

            return redirect("td:client_list_td")
        except requests.exceptions.RequestException as e:
            # Handle exceptions, log, or render an error page
            print(f"Error deleting task: {e}")
            return render(request, self.template_name, {"error": "Failed to delete task."})
        
#AREAS

class ListAreasClient(generic.View):
    template_name = "ToDo/list_areas_cl.html"
    url = "http://localhost:8000/api/areas/"
    response = None
    context = {}
    
    def get(self, request):
        self.response = requests.get(url=self.url)
        self.context = {
            "areas": self.response.json()
        }
        return render(request, self.template_name, self.context)

class CreateAreaClient(generic.View):
    template_name = "ToDo/create_area_cl.html"
    url = "http://localhost:8000/api/areas/create/"
    context = {}
    form_class = AreaForm
    
    def get(self, request):
        form = self.form_class()
        self.context = {"form": form}
        return render(request, self.template_name, self.context)
    
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            payload = form.cleaned_data
            response = requests.post(url=self.url, json=payload)
            return redirect("td:areas-list")
        else:
            self.context = {"form": form}
            return render(request, self.template_name, self.context)

class DetailAreaClient(generic.View):
    template_name = "ToDo/detail_area_cl.html"
    url = "http://localhost:8000/api/areas/"
    response = None
    
    def get(self, request, pk):
        self.url = self.url + f'{pk}/'
        self.response = requests.get(url=self.url)
        self.context = {"area": self.response.json()}
        return render(request, self.template_name, self.context)

class UpdateAreaClient(generic.View):
    template_name = "ToDo/update_area_cl.html"
    url = "http://localhost:8000/api/areas/"
    context = {}
    form_class = AreaForm
    
    def get(self, request, pk):
        area_response = requests.get(self.url + f'{pk}/')
        area_data = area_response.json()
        form = self.form_class(initial=area_data)
        self.context = {
            "form": form,
            "area_id": pk
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request, pk):
        form = self.form_class(request.POST)
        if form.is_valid():
            payload = form.cleaned_data
            response = requests.put(url=self.url + f'{pk}/update/', json=payload)
            return redirect("td:areas-list")
        else:
            self.context = {"form": form}
            return render(request, self.template_name, self.context)

class DeleteAreaClient(generic.View):
    template_name = "ToDo/delete_area_cl.html"
    url = "http://localhost:8000/api/areas/"
    
    def get(self, request, pk):
        area_response = requests.get(f"{self.url}{pk}/")
        area_data = area_response.json()
        context = {"area": area_data}
        return render(request, self.template_name, context)
    
    def post(self, request, pk):
        response = requests.delete(f"{self.url}{pk}/delete/")
        return redirect("td:areas-list")

Client/templates/grantgoal/create_gg_cl.html
{% extends "base/base.html" %}

{% block title %}NEW GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-success form-control">New GrantGoal</button>
            <a href="{% url 'gg:client_list_gg' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

Client/templates/grantgoal/detail_gg_cl.html
{% extends "base/base.html" %}

{% block title %}DETAIL GRANT GOAL VIEW{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          General Data
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          The GrantGoal name is: <strong>{{ grantgoal.ggname }}</strong> and Its Description is: {{ grantgoal.description }}, the Responsable user is: <code>{{ grantgoal.user }}</code>.
          <strong>Its progress: {{ grantgoal.progress }}</strong>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          The timestamp for the grantgoal is: <strong>{{ grantgoal.timestamp }}.</strong> Its final date is: {{ grantgoal.final_date }} and its days duration:  <code>{{ grantgoal.days_durations }}</code>.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          STATUS DATA
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          The Status for the grantgoal is: <strong>{{grantgoal.status }}</strong> Its state is: {{ grantgoal.state }} and the priority is:  <code>{{ grantgoal.priority }}</code>.
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

Client/templates/grantgoal/list_gg_cl.html
{% extends "base/base.html" %}

{% block title %} GRANT GOAL CLIENT {% endblock title%}

{% block content %}
    <a href="{% url 'gg:create_gg_cl' %}" class=" form-control btn btn-info">Create</a>
    <table class="table">
        <thead>
            <th>NAME</th>
            <th>TIMESTAMP</th>
            <th>DAYS DURATION</th>
            <th>STATE</th>
            <th>STATUS</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for gg in grantgoals %}
            <tr>
                <td>{{gg.name}}</td>
                <td>{{gg.timestamp}}</td>
                <td>{{gg.days_duration}}</td>
                <td>{{gg.state}}</td>
                <td>{{gg.status}}</td>
                <td><a href = "{% url 'gg:detail_list_gg' gg.id %}" class="btn btn-info">Detail</a></td>
                <td><a href = "" class="btn btn-warning">Update</a></td>
                <td><a href = "" class="btn btn-danger">Delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endblock content %}