Client/Client/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grantgoal/', include("grantgoal.urls"))
]

Client/grantgoal/urls.py
from django.urls import path
from grantgoal import views

app_name = "gg"

urlpatterns = [
    path("client/list/grantgoal/", views.ListGrantGoalClient.as_view(), name = "client_list_gg"),
    path("client/detail/grantgoal/<int:pk>/", views.DetailGrantGoalClient.as_view(), name = "detail_list_gg"),
    path("client/create/grantgoal/", views.CreateGrantGoalClient.as_view(), name = "create_gg_cl"),


]

api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    path('v1/list/grantgoal', views.ListGrantGoalAPIView.as_view(), name="list_gg_api"),
    path('v1/create/grantgoal', views.CreateGrantGoalAPIView.as_view(), name="create_gg_api"),
    path('v1/detail/grantgoal/<int:pk>', views.DetailGrantGoalAPIView.as_view(), name="detail_gg_api"),
    path('v1/update/grantgoal/<int:pk>', views.UpdateGrantGoalAPIView.as_view(), name="update_gg_api"),
    path('v1/delete/grantgoal/<int:pk>', views.DeleteGrantGoalAPIView.as_view(), name="delete_gg_api"),

]

examen2/Client/ToDo/urls.py
from django.urls import path
from ToDo import views

app_name = "td"

urlpatterns = [
    path("client/list/task/", views.ListTasksClient.as_view(), name = "client_list_td"),
    path('client/create/task', views.CreateTasksClient.as_view(), name = "client_create_td"),
    path('client/detail/task/<int:pk>/', views.DetailTaskClient.as_view(), name = "client_detail_td"),
    path('client/update/task/<int:pk>/', views.UpdateTasksClient.as_view(), name="client_update_td"),
    path('client/delete/task/<int:pk>/', views.DeleteTasksClient.as_view(), name="client_delete_td"),
  
  #Areas
    path('client/areas/', views.ListAreasClient.as_view(), name='areas-list'),
    path('client/areas/create/', views.CreateAreaClient.as_view(), name='areas-create'),
    path('client/areas/<int:pk>/', views.DetailAreaClient.as_view(), name='areas-detail'),
    path('client/areas/<int:pk>/update/', views.UpdateAreaClient.as_view(), name='areas-update'),
    path('client/areas/<int:pk>/delete/', views.DeleteAreaClient.as_view(), name='areas-delete'),
]

pem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

examen2/Client/ToDo/models.py
from django.db import models

# Create your models here.

Client/grantgoal/views.py
from django.shortcuts import render, redirect
from django.views import generic
import requests
from .forms import CreateGrantGoalClientForm

# Create your views here.

class CreateGrantGoalClient(generic.View):
    template_name = "grantgoal/create_gg_cl.html"
    context = {}
    url = "http://localhost:8000/api/v1/list/grantgoal"
    response = None
    payload = {}
    form_class = CreateGrantGoalClientForm
    
    def get(self, request):
        self.context = {
            "form": self.form_class
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request):
        self.payload = {
                "ggname": request.POST['ggname'],
                "description": request.POST['description'],
                "days_duration": request.POST['days_duration'],
                "priority": request.POST['priority'],
                "state": request.POST['state'],
                "status": request.POST['status'],
                "slug": request.POST['slug'],
                "user": 1 #Change this to the users data
        }
        self.response = requests.post(url=self.url, data=self.payload)
        return redirect("gg:client_list_gg")


class ListGrantGoalClient(generic.View):
    template_name = "grantgoal/list_gg_cl.html"
    url = "http://localhost:8000/api/v1/list/grantgoal"
    response = None
    context = {}
    
    def get(self, request):
        self.response = requests.get(url = self.url)
        self.context = {
            "grantgoals": self.response.json()
        }
        return render(request, self.template_name, self.context)
    
class DetailGrantGoalClient(generic.View):
    template_name = "grantgoal/detail_gg_cl.html"
    context = {}
    url = "http://localhost:8000/api/v1/detail/grantgoal/"
    response = None
    
    def get(self, request, pk):
        self.url = self.url + f'{pk}'
        self.response = requests.get(url = self.url)
        self.context = {
            "grantgoal": self.response.json()
        }
        return render(request, self.template_name, self.context)

examen2/API/ToDo/views.py
from rest_framework import generics
from ToDo.models import Task, Area, Comment, CustomUser
from ToDo.serializers import (
    DetailTaskSerializer, CreateTaskSerializer,
    AreaSerializer, CommentSerializer, UserSerializer,
    TaskIDSerializer, TaskIDTitleSerializer,
    UnresolvedTasksSerializer, ResolvedTasksSerializer,
    TaskUserIDSerializer, ResolvedTasksUserIDSerializer,
    UnresolvedTasksUserIDSerializer
)

# Task 
class ListTaskAPIView(generics.ListAPIView):
    queryset = Task.objects.all()
    serializer_class = DetailTaskSerializer

class DetailTaskAPIView(generics.RetrieveAPIView):
    queryset = Task.objects.all()
    serializer_class = DetailTaskSerializer

class CreateTaskAPIView(generics.CreateAPIView):
    queryset = Task.objects.all()
    serializer_class = CreateTaskSerializer

class UpdateTaskAPIView(generics.UpdateAPIView):
    queryset = Task.objects.all()
    serializer_class = DetailTaskSerializer

class DeleteTaskAPIView(generics.DestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = DetailTaskSerializer
    
# Asked serializers:
class ListTaskIDOnlyAPIView(generics.ListAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskIDSerializer  #only task ID
    
class ListTaskIDTitleAPIView(generics.ListAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskIDTitleSerializer  # Every task, only ID and title

class UnresolvedTasksAPIView(generics.ListAPIView):
    serializer_class = UnresolvedTasksSerializer  # Every pending task, only ID and titkes

    def get_queryset(self):
        return Task.objects.filter(state='PENDING')

class ResolvedTasksAPIView(generics.ListAPIView):
    serializer_class = ResolvedTasksSerializer  # Every resolverd task, ID and titles

    def get_queryset(self):
        return Task.objects.filter(state='DONE')

class ListTaskUserIDAPIView(generics.ListAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskUserIDSerializer  # Every task by id and user

class ResolvedTasksUserIDAPIView(generics.ListAPIView):
    serializer_class = ResolvedTasksUserIDSerializer  # every resolverd task by ID and User

    def get_queryset(self):
        return Task.objects.filter(state='DONE')

class UnresolvedTasksUserIDAPIView(generics.ListAPIView):
    serializer_class = UnresolvedTasksUserIDSerializer  # Every pending task user n ID

    def get_queryset(self):
        return Task.objects.filter(state='PENDING')

# Area 
class ListAreaAPIView(generics.ListAPIView):
    queryset = Area.objects.all()
    serializer_class = AreaSerializer

class DetailAreaAPIView(generics.RetrieveAPIView):
    queryset = Area.objects.all()
    serializer_class = AreaSerializer

class CreateAreaAPIView(generics.CreateAPIView):
    queryset = Area.objects.all()
    serializer_class = AreaSerializer

class UpdateAreaAPIView(generics.UpdateAPIView):
    queryset = Area.objects.all()
    serializer_class = AreaSerializer
    
class DeleteAreaAPIView(generics.DestroyAPIView):
    queryset = Area.objects.all()
    serializer_class = AreaSerializer

# Comment 

class DetailCommentAPIView(generics.RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

class CreateCommentAPIView(generics.CreateAPIView):
    serializer_class = CommentSerializer

    
class DeleteCommentAPIView(generics.DestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

# User    
class UserListView(generics.ListAPIView):
    queryset = CustomUser.objects.all()
    serializer_class = UserSerializer

class UserCreateView(generics.CreateAPIView):
    queryset = CustomUser.objects.all()
    serializer_class = UserSerializer

examen2/Client/ToDo/views.py
from django.shortcuts import render, redirect
from django.views import generic
import requests
from .forms import CreateTaskForm, AreaForm
# Create your views here.
class ListTasksClient(generic.View):
    template_name = "ToDo/list_todo_cl.html"
    base_url = "http://localhost:8000/api/tasks/"
    response = None
    context = {}
    
    def get(self, request):
        filter_params = {}
        selected_endpoint = request.GET.get('endpoint')
        url = self.base_url
        
        # Determine which endpoint to use based on selected option
        if selected_endpoint == 'ids':
            url += 'ids/'
        elif selected_endpoint == 'id-titles':
            url += 'id-titles/'
        elif selected_endpoint == 'unresolved':
            url += 'unresolved/'
        elif selected_endpoint == 'resolved':
            url += 'resolved/'
        elif selected_endpoint == 'userids':
            url += 'userids/'
        elif selected_endpoint == 'resolved-userids':
            url += 'resolved/userids/'
        elif selected_endpoint == 'unresolved-userids':
            url += 'unresolved/userids/'
        else:
            # Default to all tasks
            pass
        
        self.response = requests.get(url=url)
        self.context = {
            "todo": self.response.json()
        }
        return render(request, self.template_name, self.context)

class CreateTasksClient(generic.CreateView):
    template_name = "ToDo/create_todo_cl.html"
    url = "http://localhost:8000/api/tasks/create/"
    users_url = "http://localhost:8000/api/users/"
    areas_url = "http://localhost:8000/api/areas/"
    context = {}
    form_class = CreateTaskForm
    
    def get(self, request):
        users_response = requests.get(self.users_url)
        areas_response = requests.get(self.areas_url)
        
        users = [(user['id'], f"{user['first_name']} {user['last_name']}") for user in users_response.json()]
        areas = [(area['id'], area['area_name']) for area in areas_response.json()]
        
        form = self.form_class()
        form.fields['user'].choices = users
        form.fields['area'].choices = areas
        
        self.context = {
            "form": form
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request):
        payload = {
            "title": request.POST['title'],
            "description": request.POST['description'],
            "due_date": request.POST['due_date'],
            "priority": request.POST['priority'],
            "state": request.POST['state'],
            "user": request.POST['user'],
            "area": request.POST['area']
        }
        response = requests.post(url=self.url, json=payload)  
        print(payload);
        return redirect("td:client_list_td")
    
class DetailTaskClient(generic.View):
    template_name = "ToDo/detail_todo_cl.html"
    context = {}
    url = "http://localhost:8000/api/tasks/"
    response = None
    
    def get(self, request, pk):
        self.url = self.url + f'{pk}'
        self.response = requests.get(url = self.url)
        self.context = {
            "todo": self.response.json()
        }
        return render(request, self.template_name, self.context)

class UpdateTasksClient(generic.View):
    template_name = "ToDo/update_todo_cl.html"
    url = "http://localhost:8000/api/tasks/"
    users_url = "http://localhost:8000/api/users/"
    areas_url = "http://localhost:8000/api/areas/"
    context = {}
    form_class = CreateTaskForm
    
    def get(self, request, pk):
        task_response = requests.get(self.url + f'{pk}/')
        task_data = task_response.json()
        
        users_response = requests.get(self.users_url)
        areas_response = requests.get(self.areas_url)
        
        users = [(user['id'], f"{user['first_name']} {user['last_name']}") for user in users_response.json()]
        areas = [(area['id'], area['area_name']) for area in areas_response.json()]
        
        form = self.form_class(initial=task_data)
        form.fields['user'].choices = users
        form.fields['area'].choices = areas
        
        self.context = {
            "form": form,
            "task_id": pk
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request, pk):
        payload = {
            "title": request.POST['title'],
            "description": request.POST['description'],
            "due_date": request.POST['due_date'],
            "priority": request.POST['priority'],
            "state": request.POST['state'],
            "user": request.POST['user'],
            "area": request.POST['area']
        }
        response = requests.put(url=self.url + f'{pk}/update/', json=payload)  
        return redirect("td:client_list_td")

class DeleteTasksClient(generic.View):
    template_name = "ToDo/delete_todo_cl.html"
    url = "http://localhost:8000/api/tasks/"

    def get(self, request, pk):
        task_response = requests.get(f"{self.url}{pk}/")
        task_data = task_response.json()

        context = {
            "task": task_data
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        try:
            response = requests.delete(f"{self.url}{pk}/delete/")
            response.raise_for_status()  # Raise an exception for HTTP errors

            return redirect("td:client_list_td")
        except requests.exceptions.RequestException as e:
            # Handle exceptions, log, or render an error page
            print(f"Error deleting task: {e}")
            return render(request, self.template_name, {"error": "Failed to delete task."})
        
#AREAS

class ListAreasClient(generic.View):
    template_name = "ToDo/list_areas_cl.html"
    url = "http://localhost:8000/api/areas/"
    response = None
    context = {}
    
    def get(self, request):
        self.response = requests.get(url=self.url)
        self.context = {
            "areas": self.response.json()
        }
        return render(request, self.template_name, self.context)

class CreateAreaClient(generic.View):
    template_name = "ToDo/create_area_cl.html"
    url = "http://localhost:8000/api/areas/create/"
    context = {}
    form_class = AreaForm
    
    def get(self, request):
        form = self.form_class()
        self.context = {"form": form}
        return render(request, self.template_name, self.context)
    
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            payload = form.cleaned_data
            response = requests.post(url=self.url, json=payload)
            return redirect("td:areas-list")
        else:
            self.context = {"form": form}
            return render(request, self.template_name, self.context)

class DetailAreaClient(generic.View):
    template_name = "ToDo/detail_area_cl.html"
    url = "http://localhost:8000/api/areas/"
    response = None
    
    def get(self, request, pk):
        self.url = self.url + f'{pk}/'
        self.response = requests.get(url=self.url)
        self.context = {"area": self.response.json()}
        return render(request, self.template_name, self.context)

class UpdateAreaClient(generic.View):
    template_name = "ToDo/update_area_cl.html"
    url = "http://localhost:8000/api/areas/"
    context = {}
    form_class = AreaForm
    
    def get(self, request, pk):
        area_response = requests.get(self.url + f'{pk}/')
        area_data = area_response.json()
        form = self.form_class(initial=area_data)
        self.context = {
            "form": form,
            "area_id": pk
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request, pk):
        form = self.form_class(request.POST)
        if form.is_valid():
            payload = form.cleaned_data
            response = requests.put(url=self.url + f'{pk}/update/', json=payload)
            return redirect("td:areas-list")
        else:
            self.context = {"form": form}
            return render(request, self.template_name, self.context)

class DeleteAreaClient(generic.View):
    template_name = "ToDo/delete_area_cl.html"
    url = "http://localhost:8000/api/areas/"
    
    def get(self, request, pk):
        area_response = requests.get(f"{self.url}{pk}/")
        area_data = area_response.json()
        context = {"area": area_data}
        return render(request, self.template_name, context)
    
    def post(self, request, pk):
        response = requests.delete(f"{self.url}{pk}/delete/")
        return redirect("td:areas-list")

examen2/Client/templates/ToDo/create_area_cl.html
{% extends "base/base.html" %}

{% block title %}Create Area{% endblock %}

{% block content %}
<div class="container">
    <h2 class="mt-4">{{ title }}</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="area_name">Area Name</label>
            <input type="text" class="form-control" id="area_name" name="area_name" value="{{ form.area_name.value }}">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" name="description">{{ form.description.value }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary mt-3 form-control">Create</button>
        <a href="{% url 'td:areas-list' %}" class="btn btn-outline-secondary form-control">Cancel</a>

    </form>
</div>
{% endblock %}

examen2/Client/templates/ToDo/create_todo_cl.html
{% extends "base/base.html" %}

{% block title %}NEW TASK VIEW{% endblock title %}

{% block content %}
<h1>Create a Task</h1>
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <br/>
            <button type="submit" class="btn btn-outline-success form-control">New Task</button>
            <br/>
            <a href="{% url 'td:client_list_td' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

examen2/Client/templates/ToDo/delete_area_cl.html
{% extends "base/base.html" %}

{% block title %}Delete Area{% endblock %}

{% block content %}
<div class="container">
    <h2 class="mt-4">Delete Area</h2>
    <p>Are you sure you want to delete the area "{{ area.area_name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'td:areas-list' %}" class="btn btn-secondary form-control">Cancel</a>
        <a href="{% url 'td:areas-list' %}" class="btn btn-outline-secondary form-control">Cancel</a>

    </form>
</div>
{% endblock %}

examen2/Client/templates/ToDo/delete_todo_cl.html
{% extends "base/base.html" %}

{% block title %}DELETE TASK VIEW{% endblock title %}

{% block content %}
<h1>Delete Task</h1>
<p>Are you sure you want to delete "{{ task.title }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-danger form-control">Delete</button>
    <a href="{% url 'td:client_list_td' %}" class="btn btn-outline-secondary form-control">Cancel</a>
</form>
{% endblock content %}

examen2/Client/templates/ToDo/detail_area_cl.html
{% extends "base/base.html" %}

{% block title %}Area Detail{% endblock %}

{% block content %}
<div class="container">
    <h2 class="mt-4">Area Detail</h2>
    <p><strong>ID:</strong> {{ area.id }}</p>
    <p><strong>Area Name:</strong> {{ area.area_name }}</p>
    <p><strong>Description:</strong> {{ area.description }}</p>
    <a href="{% url 'td:areas-update' area.id %}" class="btn btn-warning">Update</a>
    <a href="{% url 'td:areas-delete' area.id %}" class="btn btn-danger">Delete</a>
    <a href="{% url 'td:areas-list' %}" class="btn btn-secondary">Back to List</a>
</div>
{% endblock %}

examen2/Client/templates/ToDo/detail_todo_cl.html
{% extends "base/base.html" %}

{% block title %}DETAIL TASK VIEW{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                General Data
            </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <p>The Task name is: <strong>{{ todo.title }}</strong> and Its Description is: {{ todo.description }}, the Assignee user is: <code>{{ todo.user }}</code>.</p>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Date Data
            </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <p>The timestamp for the Task is: <strong>{{ todo.created_at }}.</strong> Its due date is: <strong>{{ todo.due_date }}</strong></p>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Status Data
            </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <p>The state for the Task is: <strong>{{ todo.state }}</strong> and the priority is: <code>{{ todo.priority }}</code>.</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

examen2/Client/templates/ToDo/list_areas_cl.html
{% extends "base/base.html" %}

{% block title %}Areas{% endblock %}

{% block content %}
<nav class="navbar bg-body-tertiary">
    <div class="container-fluid d-flex justify-content-between align-items-center">
        <div>
            <a href="{% url 'td:areas-create' %}" class="btn btn-success">Create Area</a>
        </div>
    </div>
</nav>

<hr/>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Area Name</th>
            <th>Description</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for area in areas %}
        <tr>
            <td>{{ area.id }}</td>
            <td>{{ area.area_name }}</td>
            <td>{{ area.description }}</td>
            <td>
                <a href="{% url 'td:areas-detail' area.id %}" class="btn btn-info btn-sm">Detail</a>
                <a href="{% url 'td:areas-update' area.id %}" class="btn btn-warning btn-sm">Update</a>
                <a href="{% url 'td:areas-delete' area.id %}" class="btn btn-danger btn-sm">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

examen2/Client/templates/ToDo/list_todo_cl.html
{% extends "base/base.html" %}

{% block title %} TODO CLIENT {% endblock title %}

{% block content %}
<nav class="navbar bg-body-tertiary">
    <div class="container-fluid d-flex justify-content-between align-items-center">
        <div>
            <a href="{% url 'td:client_create_td' %}" class="btn btn-success">Create Task</a>
        </div>
        <form class="form-inline" method="GET">
            <div class="form-group mb-0">
                <select class="form-control" id="endpoint_filter" name="endpoint">
                    <option value="">All</option>
                    <option value="ids">Task IDs</option>
                    <option value="id-titles">Task IDs and Titles</option>
                    <option value="unresolved">Unresolved Tasks</option>
                    <option value="resolved">Resolved Tasks</option>
                    <option value="userids">Task IDs and User IDs</option>
                    <option value="resolved-userids">Resolved Task IDs and User IDs</option>
                    <option value="unresolved-userids">Unresolved Task IDs and User IDs</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary ml-2">Apply Filter</button>
        </form>
    </div>
</nav>

<hr/>
<div class="row">
    {% for td in todo %}
    <div class="col-md-4 mb-4">
        <div class="card">
            <div class="card-body">
                {% if endpoint == 'ids' %}
                    <h5 class="card-title">Task ID: {{ td.id }}</h5>
                {% elif endpoint == 'id-titles' %}
                    <h5 class="card-title">{{ td.title }}</h5>
                    <p class="card-text">Task ID: {{ td.id }}</p>
                {% else %}
                    <h5 class="card-title">{{ td.title }}</h5>
                    <p class="card-text">Due Date: {{ td.due_date }}</p>
                    <p class="card-text">Priority: {{ td.priority }}</p>
                    <p class="card-text">State: {{ td.state }}</p>
                {% endif %}
                
                <a href="{% url 'td:client_detail_td' td.id  %}" class="btn btn-info mr-2">Detail</a>
                <a href="{% url 'td:client_update_td' td.id %}" class="btn btn-warning mr-2">Update</a>
                <a href="{% url 'td:client_delete_td' td.id %}" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

examen2/Client/templates/ToDo/update_area_cl.html
{% extends "base/base.html" %}

{% block title %}Update Area{% endblock %}

{% block content %}
<div class="container">
    <h2 class="mt-4">{{ title }}</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="area_name">Area Name</label>
            <input type="text" class="form-control" id="area_name" name="area_name" value="{{ form.area_name.value }}">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" name="description">{{ form.description.value }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary mt-3 form-control">Update</button>
        <a href="{% url 'td:areas-list' %}" class="btn btn-outline-secondary form-control">Cancel</a>

    </form>
</div>
{% endblock %}

examen2/Client/templates/ToDo/update_todo_cl.html
{% extends "base/base.html" %}

{% block title %}UPDATE TASK VIEW{% endblock title %}

{% block content %}
<h1>Update Task</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-primary form-control">Update Task</button>
    <a href="{% url 'td:client_list_td' %}" class="btn btn-outline-warning form-control">Cancel</a>
</form>
{% endblock content %}